FROM microsoft/dotnet:1.1.1-sdk
WORKDIR /dotnetapp

RUN mkdir -p /dotnetapp
COPY Wukong.sln .
COPY Wukong ./Wukong
COPY Wukong.Tests ./Wukong.Tests

RUN dotnet restore
# Publish linux version.
RUN dotnet publish Wukong/Wukong.csproj -c Release -o ../wukong-linux-x64 -r debian.8-x64
RUN tar czvf wukong-linux-x64.tar.gz wukong-linux-x64/

EXPOSE 5000
CMD ["./wukong-linux-x64/Wukong"]
