wukong:
  build: .
  privileged: false
  restart: always
  ports:
  - 5000:5000
  environment:
  - WUKONG_PROVIDER=https://api2.wukongmusic.us/
  - APPLICATION_INSIGHTS_INSTRUMENTATION_KEY=61dd0db-f6fe-4a0d-9e18-e784d05ae0a3
  - GOOGLE_CLIENT_ID=682153077625-p7ivd3omq8o322b8vp5dpqf29uf3cq5u.apps.googleusercontent.com
  - GOOGLE_CLIENT_SECRET=K2EqrVIUCadf7mA8ofsd_kJm
  - GITHUB_CLIENT_ID=eefa75a1222b540c9b59
  - GITHUB_CLIENT_SECRET=ae1672ce78b2fea2a7d28207a2f570d900fba6c5
  - MICROSOFT_CLIENT_ID=64b46716-28d2-4f3b-bb02-5a7d1d7fb9de
  - MICROSOFT_CLIENT_SECRET=kh5p1fFejsXOAwdTHYgkVqo
