FROM microsoft/dotnet:1.1.1-sdk
WORKDIR /dotnetapp

RUN mkdir -p /dotnetapp
COPY Wukong.sln .
COPY WukongNew ./WukongNew
RUN dotnet restore
# Publish to /dotnetapp/wukong-dist
RUN dotnet publish -c Release -o ../wukong-dist_linux-x64 -r debian.8-x64

COPY appsettings.template.json .

COPY start.sh /
RUN chmod +x /start.sh

EXPOSE 5000
CMD ["/start.sh"]
